#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 1

enum {
  sym__space = 1,
  sym_newline = 2,
  anon_sym_BQUOTE = 3,
  sym_slur_open = 4,
  sym_slur_close = 5,
  aux_sym_note_construct_token1 = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  sym_alteration = 9,
  sym_note_letter = 10,
  sym_octave = 11,
  sym_rest = 12,
  anon_sym_Z = 13,
  anon_sym_X = 14,
  aux_sym_multimeasure_rest_token1 = 15,
  sym_rhythm = 16,
  aux_sym_grace_note_token1 = 17,
  aux_sym_grace_note_token2 = 18,
  aux_sym_chord_symbol_token1 = 19,
  aux_sym_chord_symbol_token2 = 20,
  sym_annotation = 21,
  sym_tuplet_marker = 22,
  sym_chord_type = 23,
  sym_decoration_shorthand = 24,
  sym_source_file = 25,
  sym_music_content = 26,
  sym_nte_or_chrd = 27,
  sym_beam = 28,
  sym_note_construct = 29,
  sym_chord_cstrct = 30,
  sym_note = 31,
  sym_chord_note = 32,
  sym_pitch = 33,
  sym_multimeasure_rest = 34,
  sym_grace_note = 35,
  sym_chord_symbol_note = 36,
  sym_chord_symbol = 37,
  sym_decoration = 38,
  aux_sym_beam_repeat1 = 39,
  aux_sym_beam_repeat2 = 40,
  aux_sym_note_construct_repeat1 = 41,
  aux_sym_chord_cstrct_repeat1 = 42,
  aux_sym_pitch_repeat1 = 43,
  aux_sym_grace_note_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__space] = "_space",
  [sym_newline] = "newline",
  [anon_sym_BQUOTE] = "`",
  [sym_slur_open] = "slur_open",
  [sym_slur_close] = "slur_close",
  [aux_sym_note_construct_token1] = "note_construct_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_alteration] = "alteration",
  [sym_note_letter] = "note_letter",
  [sym_octave] = "octave",
  [sym_rest] = "rest",
  [anon_sym_Z] = "Z",
  [anon_sym_X] = "X",
  [aux_sym_multimeasure_rest_token1] = "multimeasure_rest_token1",
  [sym_rhythm] = "rhythm",
  [aux_sym_grace_note_token1] = "grace_note_token1",
  [aux_sym_grace_note_token2] = "grace_note_token2",
  [aux_sym_chord_symbol_token1] = "chord_symbol_token1",
  [aux_sym_chord_symbol_token2] = "chord_symbol_token2",
  [sym_annotation] = "annotation",
  [sym_tuplet_marker] = "tuplet_marker",
  [sym_chord_type] = "chord_type",
  [sym_decoration_shorthand] = "decoration_shorthand",
  [sym_source_file] = "source_file",
  [sym_music_content] = "music_content",
  [sym_nte_or_chrd] = "nte_or_chrd",
  [sym_beam] = "beam",
  [sym_note_construct] = "note_construct",
  [sym_chord_cstrct] = "chord_cstrct",
  [sym_note] = "note",
  [sym_chord_note] = "chord_note",
  [sym_pitch] = "pitch",
  [sym_multimeasure_rest] = "multimeasure_rest",
  [sym_grace_note] = "grace_note",
  [sym_chord_symbol_note] = "chord_symbol_note",
  [sym_chord_symbol] = "chord_symbol",
  [sym_decoration] = "decoration",
  [aux_sym_beam_repeat1] = "beam_repeat1",
  [aux_sym_beam_repeat2] = "beam_repeat2",
  [aux_sym_note_construct_repeat1] = "note_construct_repeat1",
  [aux_sym_chord_cstrct_repeat1] = "chord_cstrct_repeat1",
  [aux_sym_pitch_repeat1] = "pitch_repeat1",
  [aux_sym_grace_note_repeat1] = "grace_note_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__space] = sym__space,
  [sym_newline] = sym_newline,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_slur_open] = sym_slur_open,
  [sym_slur_close] = sym_slur_close,
  [aux_sym_note_construct_token1] = aux_sym_note_construct_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_alteration] = sym_alteration,
  [sym_note_letter] = sym_note_letter,
  [sym_octave] = sym_octave,
  [sym_rest] = sym_rest,
  [anon_sym_Z] = anon_sym_Z,
  [anon_sym_X] = anon_sym_X,
  [aux_sym_multimeasure_rest_token1] = aux_sym_multimeasure_rest_token1,
  [sym_rhythm] = sym_rhythm,
  [aux_sym_grace_note_token1] = aux_sym_grace_note_token1,
  [aux_sym_grace_note_token2] = aux_sym_grace_note_token2,
  [aux_sym_chord_symbol_token1] = aux_sym_chord_symbol_token1,
  [aux_sym_chord_symbol_token2] = aux_sym_chord_symbol_token2,
  [sym_annotation] = sym_annotation,
  [sym_tuplet_marker] = sym_tuplet_marker,
  [sym_chord_type] = sym_chord_type,
  [sym_decoration_shorthand] = sym_decoration_shorthand,
  [sym_source_file] = sym_source_file,
  [sym_music_content] = sym_music_content,
  [sym_nte_or_chrd] = sym_nte_or_chrd,
  [sym_beam] = sym_beam,
  [sym_note_construct] = sym_note_construct,
  [sym_chord_cstrct] = sym_chord_cstrct,
  [sym_note] = sym_note,
  [sym_chord_note] = sym_chord_note,
  [sym_pitch] = sym_pitch,
  [sym_multimeasure_rest] = sym_multimeasure_rest,
  [sym_grace_note] = sym_grace_note,
  [sym_chord_symbol_note] = sym_chord_symbol_note,
  [sym_chord_symbol] = sym_chord_symbol,
  [sym_decoration] = sym_decoration,
  [aux_sym_beam_repeat1] = aux_sym_beam_repeat1,
  [aux_sym_beam_repeat2] = aux_sym_beam_repeat2,
  [aux_sym_note_construct_repeat1] = aux_sym_note_construct_repeat1,
  [aux_sym_chord_cstrct_repeat1] = aux_sym_chord_cstrct_repeat1,
  [aux_sym_pitch_repeat1] = aux_sym_pitch_repeat1,
  [aux_sym_grace_note_repeat1] = aux_sym_grace_note_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_slur_open] = {
    .visible = true,
    .named = true,
  },
  [sym_slur_close] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_construct_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_alteration] = {
    .visible = true,
    .named = true,
  },
  [sym_note_letter] = {
    .visible = true,
    .named = true,
  },
  [sym_octave] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multimeasure_rest_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_rhythm] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_grace_note_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grace_note_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chord_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chord_symbol_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_tuplet_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_chord_type] = {
    .visible = true,
    .named = true,
  },
  [sym_decoration_shorthand] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_music_content] = {
    .visible = true,
    .named = true,
  },
  [sym_nte_or_chrd] = {
    .visible = true,
    .named = true,
  },
  [sym_beam] = {
    .visible = true,
    .named = true,
  },
  [sym_note_construct] = {
    .visible = true,
    .named = true,
  },
  [sym_chord_cstrct] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_chord_note] = {
    .visible = true,
    .named = true,
  },
  [sym_pitch] = {
    .visible = true,
    .named = true,
  },
  [sym_multimeasure_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_grace_note] = {
    .visible = true,
    .named = true,
  },
  [sym_chord_symbol_note] = {
    .visible = true,
    .named = true,
  },
  [sym_chord_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_decoration] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_beam_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_beam_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_construct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chord_cstrct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pitch_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grace_note_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 88,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == '=' ||
          (9837 <= lookahead && lookahead <= 9839) ||
          lookahead == 119082 ||
          lookahead == 119083) ADVANCE(22);
      if (lookahead == 'X') ADVANCE(29);
      if (lookahead == 'Z') ADVANCE(28);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '^') ADVANCE(23);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\'' ||
          lookahead == ',') ADVANCE(26);
      if (('<' <= lookahead && lookahead <= '>')) ADVANCE(35);
      if (lookahead == 'x' ||
          lookahead == 'z') ADVANCE(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '.' ||
          lookahead == 'H' ||
          lookahead == 'L' ||
          lookahead == 'M' ||
          lookahead == 'O' ||
          lookahead == 'P' ||
          lookahead == 'S' ||
          lookahead == 'T' ||
          lookahead == 'u' ||
          lookahead == 'v' ||
          lookahead == '~') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'G') ||
          ('a' <= lookahead && lookahead <= 'g')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead == '7' ||
          lookahead == '9') ADVANCE(74);
      if (lookahead == '=' ||
          (9837 <= lookahead && lookahead <= 9839) ||
          lookahead == 119082 ||
          lookahead == 119083) ADVANCE(22);
      if (lookahead == '^') ADVANCE(23);
      if (lookahead == '_') ADVANCE(47);
      if (lookahead == 'a') ADVANCE(72);
      if (lookahead == 'd') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(48);
      if (lookahead == 's') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '8') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '=' ||
          (9837 <= lookahead && lookahead <= 9839) ||
          lookahead == 119082 ||
          lookahead == 119083) ADVANCE(22);
      if (lookahead == '^') ADVANCE(23);
      if (lookahead == '_') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '=' ||
          (9837 <= lookahead && lookahead <= 9839) ||
          lookahead == 119082 ||
          lookahead == 119083) ADVANCE(22);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '^') ADVANCE(23);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\'' ||
          lookahead == ',') ADVANCE(26);
      if (('<' <= lookahead && lookahead <= '>')) ADVANCE(35);
      if (lookahead == 'x' ||
          lookahead == 'z') ADVANCE(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead == '.' ||
          lookahead == 'H' ||
          lookahead == 'L' ||
          lookahead == 'M' ||
          lookahead == 'O' ||
          lookahead == 'P' ||
          lookahead == 'S' ||
          lookahead == 'T' ||
          lookahead == 'u' ||
          lookahead == 'v' ||
          lookahead == '~') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'G') ||
          ('a' <= lookahead && lookahead <= 'g')) ADVANCE(25);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_slur_open);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_slur_close);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_note_construct_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_alteration);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_alteration);
      if (lookahead == '^') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_alteration);
      if (lookahead == '_') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_note_letter);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_octave);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_rest);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_Z);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_multimeasure_rest_token1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '0') ADVANCE(31);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_multimeasure_rest_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_rhythm);
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_rhythm);
      if (lookahead == '/') ADVANCE(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_rhythm);
      if (lookahead == '/') ADVANCE(8);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_rhythm);
      if (lookahead == '<' ||
          lookahead == '>') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_rhythm);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_grace_note_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_grace_note_token1);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_grace_note_token2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_chord_symbol_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_chord_symbol_token1);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_chord_symbol_token2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_annotation);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tuplet_marker);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tuplet_marker);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_tuplet_marker);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == '_') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == 'i') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'd') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'd') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'e') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'g') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'h') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'i') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'i') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'j') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'm') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'm') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'n') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'o') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'p') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'r') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 's') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 's') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'u') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_chord_type);
      if (lookahead == 'u') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_chord_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_decoration_shorthand);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__space] = ACTIONS(3),
    [sym_newline] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_slur_open] = ACTIONS(1),
    [sym_slur_close] = ACTIONS(1),
    [aux_sym_note_construct_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_alteration] = ACTIONS(1),
    [sym_note_letter] = ACTIONS(1),
    [sym_octave] = ACTIONS(1),
    [sym_rest] = ACTIONS(1),
    [anon_sym_Z] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [aux_sym_multimeasure_rest_token1] = ACTIONS(1),
    [sym_rhythm] = ACTIONS(1),
    [aux_sym_grace_note_token1] = ACTIONS(1),
    [aux_sym_grace_note_token2] = ACTIONS(1),
    [aux_sym_chord_symbol_token1] = ACTIONS(1),
    [aux_sym_chord_symbol_token2] = ACTIONS(1),
    [sym_annotation] = ACTIONS(1),
    [sym_tuplet_marker] = ACTIONS(1),
    [sym_decoration_shorthand] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(105),
    [sym_music_content] = STATE(104),
    [sym_nte_or_chrd] = STATE(2),
    [sym_beam] = STATE(99),
    [sym_note_construct] = STATE(51),
    [sym_chord_cstrct] = STATE(51),
    [sym_note] = STATE(33),
    [sym_pitch] = STATE(16),
    [sym_multimeasure_rest] = STATE(99),
    [sym_grace_note] = STATE(11),
    [sym_chord_symbol] = STATE(54),
    [sym_decoration] = STATE(79),
    [aux_sym_note_construct_repeat1] = STATE(11),
    [sym__space] = ACTIONS(3),
    [sym_newline] = ACTIONS(3),
    [sym_slur_open] = ACTIONS(5),
    [sym_slur_close] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_alteration] = ACTIONS(11),
    [sym_note_letter] = ACTIONS(13),
    [sym_rest] = ACTIONS(15),
    [anon_sym_Z] = ACTIONS(17),
    [anon_sym_X] = ACTIONS(17),
    [aux_sym_grace_note_token1] = ACTIONS(19),
    [aux_sym_chord_symbol_token1] = ACTIONS(21),
    [sym_annotation] = ACTIONS(23),
    [sym_tuplet_marker] = ACTIONS(25),
    [sym_decoration_shorthand] = ACTIONS(27),
  },
  [2] = {
    [sym_nte_or_chrd] = STATE(4),
    [sym_note_construct] = STATE(51),
    [sym_chord_cstrct] = STATE(51),
    [sym_note] = STATE(33),
    [sym_pitch] = STATE(16),
    [sym_grace_note] = STATE(11),
    [sym_chord_symbol] = STATE(54),
    [sym_decoration] = STATE(79),
    [aux_sym_beam_repeat1] = STATE(4),
    [aux_sym_beam_repeat2] = STATE(91),
    [aux_sym_note_construct_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__space] = ACTIONS(3),
    [sym_newline] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_alteration] = ACTIONS(11),
    [sym_note_letter] = ACTIONS(13),
    [sym_rest] = ACTIONS(15),
    [aux_sym_grace_note_token1] = ACTIONS(19),
    [aux_sym_chord_symbol_token1] = ACTIONS(21),
    [sym_annotation] = ACTIONS(33),
    [sym_tuplet_marker] = ACTIONS(35),
    [sym_decoration_shorthand] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym_alteration,
    ACTIONS(45), 1,
      sym_note_letter,
    ACTIONS(48), 1,
      sym_rest,
    ACTIONS(51), 1,
      aux_sym_grace_note_token1,
    ACTIONS(54), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(57), 1,
      sym_annotation,
    ACTIONS(60), 1,
      sym_tuplet_marker,
    ACTIONS(63), 1,
      sym_decoration_shorthand,
    STATE(16), 1,
      sym_pitch,
    STATE(33), 1,
      sym_note,
    STATE(54), 1,
      sym_chord_symbol,
    STATE(79), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(3), 2,
      sym_nte_or_chrd,
      aux_sym_beam_repeat1,
    STATE(11), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
    STATE(51), 2,
      sym_note_construct,
      sym_chord_cstrct,
  [59] = 18,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(21), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(33), 1,
      sym_annotation,
    ACTIONS(35), 1,
      sym_tuplet_marker,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_pitch,
    STATE(33), 1,
      sym_note,
    STATE(54), 1,
      sym_chord_symbol,
    STATE(79), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(3), 2,
      sym_nte_or_chrd,
      aux_sym_beam_repeat1,
    STATE(11), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
    STATE(51), 2,
      sym_note_construct,
      sym_chord_cstrct,
  [118] = 17,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(21), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(33), 1,
      sym_annotation,
    ACTIONS(35), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(33), 1,
      sym_note,
    STATE(54), 1,
      sym_chord_symbol,
    STATE(79), 1,
      sym_decoration,
    STATE(93), 1,
      sym_nte_or_chrd,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(11), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
    STATE(51), 2,
      sym_note_construct,
      sym_chord_cstrct,
  [173] = 5,
    ACTIONS(70), 1,
      sym_octave,
    ACTIONS(73), 1,
      aux_sym_chord_symbol_token1,
    STATE(6), 1,
      aux_sym_pitch_repeat1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(68), 14,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_rhythm,
      aux_sym_grace_note_token1,
      aux_sym_grace_note_token2,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [203] = 5,
    ACTIONS(77), 1,
      sym_octave,
    ACTIONS(79), 1,
      aux_sym_chord_symbol_token1,
    STATE(6), 1,
      aux_sym_pitch_repeat1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(75), 14,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_rhythm,
      aux_sym_grace_note_token1,
      aux_sym_grace_note_token2,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [233] = 5,
    ACTIONS(77), 1,
      sym_octave,
    ACTIONS(83), 1,
      aux_sym_chord_symbol_token1,
    STATE(6), 1,
      aux_sym_pitch_repeat1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(81), 14,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_rhythm,
      aux_sym_grace_note_token1,
      aux_sym_grace_note_token2,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [263] = 5,
    ACTIONS(87), 1,
      sym_octave,
    ACTIONS(89), 1,
      aux_sym_chord_symbol_token1,
    STATE(7), 1,
      aux_sym_pitch_repeat1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(85), 14,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_rhythm,
      aux_sym_grace_note_token1,
      aux_sym_grace_note_token2,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [293] = 5,
    ACTIONS(79), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(91), 1,
      sym_octave,
    STATE(8), 1,
      aux_sym_pitch_repeat1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(75), 14,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_rhythm,
      aux_sym_grace_note_token1,
      aux_sym_grace_note_token2,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [323] = 15,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(21), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      sym_annotation,
    ACTIONS(97), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(56), 1,
      sym_chord_symbol,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(45), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [371] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [414] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [457] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [500] = 13,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    ACTIONS(109), 1,
      sym_alteration,
    ACTIONS(112), 1,
      sym_note_letter,
    ACTIONS(115), 1,
      sym_rest,
    ACTIONS(118), 1,
      aux_sym_grace_note_token1,
    ACTIONS(121), 1,
      sym_annotation,
    ACTIONS(124), 1,
      sym_decoration_shorthand,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [543] = 4,
    ACTIONS(129), 1,
      sym_rhythm,
    ACTIONS(131), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(127), 12,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [568] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [611] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    ACTIONS(135), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [654] = 13,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(15), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [697] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(13), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [737] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(19), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [777] = 3,
    ACTIONS(141), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(139), 12,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      aux_sym_note_construct_token1,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [799] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(17), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [839] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(14), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [879] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(12), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [919] = 12,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(101), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(67), 1,
      sym_note,
    STATE(82), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(18), 2,
      sym_chord_note,
      aux_sym_chord_cstrct_repeat1,
    STATE(48), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [959] = 4,
    ACTIONS(145), 1,
      aux_sym_note_construct_token1,
    ACTIONS(147), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [982] = 4,
    ACTIONS(151), 1,
      aux_sym_note_construct_token1,
    ACTIONS(153), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1005] = 4,
    ACTIONS(157), 1,
      aux_sym_note_construct_token1,
    ACTIONS(159), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(155), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1028] = 4,
    ACTIONS(163), 1,
      sym_rhythm,
    ACTIONS(165), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(161), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1051] = 4,
    ACTIONS(169), 1,
      sym_rhythm,
    ACTIONS(171), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(167), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1074] = 4,
    ACTIONS(175), 1,
      aux_sym_note_construct_token1,
    ACTIONS(177), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1097] = 4,
    ACTIONS(181), 1,
      aux_sym_note_construct_token1,
    ACTIONS(183), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(179), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1120] = 4,
    ACTIONS(187), 1,
      sym_rhythm,
    ACTIONS(189), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(185), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1143] = 4,
    ACTIONS(193), 1,
      sym_rhythm,
    ACTIONS(195), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(191), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1166] = 4,
    ACTIONS(199), 1,
      sym_rhythm,
    ACTIONS(201), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(197), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1189] = 4,
    ACTIONS(205), 1,
      sym_rhythm,
    ACTIONS(207), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(203), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1212] = 4,
    ACTIONS(211), 1,
      aux_sym_note_construct_token1,
    ACTIONS(213), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(209), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1235] = 3,
    ACTIONS(217), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(215), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1255] = 3,
    ACTIONS(213), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(209), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1275] = 3,
    ACTIONS(207), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(203), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1295] = 3,
    ACTIONS(147), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1315] = 3,
    ACTIONS(195), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(191), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1335] = 3,
    ACTIONS(159), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(155), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1355] = 5,
    ACTIONS(221), 1,
      aux_sym_grace_note_token1,
    ACTIONS(224), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(45), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
    ACTIONS(219), 7,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1379] = 3,
    ACTIONS(165), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(161), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1399] = 3,
    ACTIONS(177), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1419] = 11,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(19), 1,
      aux_sym_grace_note_token1,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(226), 1,
      sym_annotation,
    STATE(16), 1,
      sym_pitch,
    STATE(70), 1,
      sym_note,
    STATE(83), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(45), 2,
      sym_grace_note,
      aux_sym_note_construct_repeat1,
  [1455] = 3,
    ACTIONS(171), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(167), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1475] = 3,
    ACTIONS(189), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(185), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1495] = 3,
    ACTIONS(230), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(228), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1515] = 3,
    ACTIONS(234), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(232), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1535] = 3,
    ACTIONS(153), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1555] = 11,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      sym_annotation,
    ACTIONS(97), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1590] = 11,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1625] = 11,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(236), 1,
      anon_sym_LBRACK,
    ACTIONS(238), 1,
      sym_annotation,
    ACTIONS(240), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(29), 1,
      sym_note,
    STATE(76), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1660] = 10,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(236), 1,
      anon_sym_LBRACK,
    ACTIONS(240), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(29), 1,
      sym_note,
    STATE(76), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1692] = 10,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1724] = 3,
    ACTIONS(244), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(242), 8,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1742] = 10,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1774] = 10,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    ACTIONS(248), 1,
      sym_tuplet_marker,
    STATE(16), 1,
      sym_pitch,
    STATE(38), 1,
      sym_note,
    STATE(78), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1806] = 9,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(236), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(29), 1,
      sym_note,
    STATE(76), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1835] = 9,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(32), 1,
      sym_note,
    STATE(77), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1864] = 9,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    STATE(80), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1893] = 9,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(38), 1,
      sym_note,
    STATE(78), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [1922] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(252), 7,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_decoration_shorthand,
  [1936] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(254), 7,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_decoration_shorthand,
  [1950] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(256), 7,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [1964] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(258), 7,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_decoration_shorthand,
  [1978] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(260), 7,
      anon_sym_RBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      aux_sym_grace_note_token1,
      sym_annotation,
      sym_decoration_shorthand,
  [1992] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(262), 7,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [2006] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(264), 7,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [2020] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(266), 7,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
      sym_annotation,
      sym_tuplet_marker,
      sym_decoration_shorthand,
  [2034] = 8,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    STATE(16), 1,
      sym_pitch,
    STATE(69), 1,
      sym_note,
    STATE(85), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2060] = 8,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(27), 1,
      sym_decoration_shorthand,
    STATE(16), 1,
      sym_pitch,
    STATE(70), 1,
      sym_note,
    STATE(83), 1,
      sym_decoration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2086] = 7,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(38), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2109] = 7,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(268), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(28), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2132] = 7,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(32), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2155] = 7,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(27), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2178] = 7,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    ACTIONS(236), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_pitch,
    STATE(29), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2201] = 5,
    ACTIONS(270), 1,
      sym_alteration,
    ACTIONS(273), 1,
      sym_note_letter,
    ACTIONS(276), 1,
      aux_sym_grace_note_token2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(81), 2,
      sym_pitch,
      aux_sym_grace_note_repeat1,
  [2219] = 6,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    STATE(16), 1,
      sym_pitch,
    STATE(70), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2239] = 6,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    STATE(16), 1,
      sym_pitch,
    STATE(69), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2259] = 5,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(278), 1,
      aux_sym_grace_note_token2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(81), 2,
      sym_pitch,
      aux_sym_grace_note_repeat1,
  [2277] = 6,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(15), 1,
      sym_rest,
    STATE(16), 1,
      sym_pitch,
    STATE(66), 1,
      sym_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2297] = 4,
    ACTIONS(11), 1,
      sym_alteration,
    ACTIONS(13), 1,
      sym_note_letter,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    STATE(84), 2,
      sym_pitch,
      aux_sym_grace_note_repeat1,
  [2312] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(280), 4,
      anon_sym_LBRACK,
      sym_alteration,
      sym_note_letter,
      sym_rest,
  [2323] = 3,
    ACTIONS(282), 1,
      sym_alteration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(284), 3,
      aux_sym_chord_symbol_token1,
      aux_sym_chord_symbol_token2,
      sym_chord_type,
  [2336] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(286), 3,
      aux_sym_chord_symbol_token1,
      aux_sym_chord_symbol_token2,
      sym_chord_type,
  [2346] = 4,
    ACTIONS(288), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(290), 1,
      aux_sym_chord_symbol_token2,
    ACTIONS(292), 1,
      sym_chord_type,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2360] = 4,
    ACTIONS(31), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(92), 1,
      aux_sym_beam_repeat2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2374] = 4,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
    ACTIONS(296), 1,
      anon_sym_BQUOTE,
    STATE(92), 1,
      aux_sym_beam_repeat2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2388] = 2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
    ACTIONS(294), 2,
      ts_builtin_sym_end,
      anon_sym_BQUOTE,
  [2397] = 3,
    ACTIONS(299), 1,
      sym_note_letter,
    STATE(106), 1,
      sym_chord_symbol_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2408] = 3,
    ACTIONS(299), 1,
      sym_note_letter,
    STATE(101), 1,
      sym_chord_symbol_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2419] = 3,
    ACTIONS(301), 1,
      sym_note_letter,
    STATE(90), 1,
      sym_chord_symbol_note,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2430] = 3,
    ACTIONS(303), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(305), 1,
      aux_sym_chord_symbol_token2,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2441] = 3,
    ACTIONS(284), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(307), 1,
      sym_alteration,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2452] = 2,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2460] = 2,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2468] = 2,
    ACTIONS(311), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2476] = 2,
    ACTIONS(313), 1,
      sym_note_letter,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2484] = 2,
    ACTIONS(315), 1,
      aux_sym_multimeasure_rest_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2492] = 2,
    ACTIONS(317), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2500] = 2,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
  [2508] = 2,
    ACTIONS(321), 1,
      aux_sym_chord_symbol_token1,
    ACTIONS(3), 2,
      sym__space,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 59,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 173,
  [SMALL_STATE(7)] = 203,
  [SMALL_STATE(8)] = 233,
  [SMALL_STATE(9)] = 263,
  [SMALL_STATE(10)] = 293,
  [SMALL_STATE(11)] = 323,
  [SMALL_STATE(12)] = 371,
  [SMALL_STATE(13)] = 414,
  [SMALL_STATE(14)] = 457,
  [SMALL_STATE(15)] = 500,
  [SMALL_STATE(16)] = 543,
  [SMALL_STATE(17)] = 568,
  [SMALL_STATE(18)] = 611,
  [SMALL_STATE(19)] = 654,
  [SMALL_STATE(20)] = 697,
  [SMALL_STATE(21)] = 737,
  [SMALL_STATE(22)] = 777,
  [SMALL_STATE(23)] = 799,
  [SMALL_STATE(24)] = 839,
  [SMALL_STATE(25)] = 879,
  [SMALL_STATE(26)] = 919,
  [SMALL_STATE(27)] = 959,
  [SMALL_STATE(28)] = 982,
  [SMALL_STATE(29)] = 1005,
  [SMALL_STATE(30)] = 1028,
  [SMALL_STATE(31)] = 1051,
  [SMALL_STATE(32)] = 1074,
  [SMALL_STATE(33)] = 1097,
  [SMALL_STATE(34)] = 1120,
  [SMALL_STATE(35)] = 1143,
  [SMALL_STATE(36)] = 1166,
  [SMALL_STATE(37)] = 1189,
  [SMALL_STATE(38)] = 1212,
  [SMALL_STATE(39)] = 1235,
  [SMALL_STATE(40)] = 1255,
  [SMALL_STATE(41)] = 1275,
  [SMALL_STATE(42)] = 1295,
  [SMALL_STATE(43)] = 1315,
  [SMALL_STATE(44)] = 1335,
  [SMALL_STATE(45)] = 1355,
  [SMALL_STATE(46)] = 1379,
  [SMALL_STATE(47)] = 1399,
  [SMALL_STATE(48)] = 1419,
  [SMALL_STATE(49)] = 1455,
  [SMALL_STATE(50)] = 1475,
  [SMALL_STATE(51)] = 1495,
  [SMALL_STATE(52)] = 1515,
  [SMALL_STATE(53)] = 1535,
  [SMALL_STATE(54)] = 1555,
  [SMALL_STATE(55)] = 1590,
  [SMALL_STATE(56)] = 1625,
  [SMALL_STATE(57)] = 1660,
  [SMALL_STATE(58)] = 1692,
  [SMALL_STATE(59)] = 1724,
  [SMALL_STATE(60)] = 1742,
  [SMALL_STATE(61)] = 1774,
  [SMALL_STATE(62)] = 1806,
  [SMALL_STATE(63)] = 1835,
  [SMALL_STATE(64)] = 1864,
  [SMALL_STATE(65)] = 1893,
  [SMALL_STATE(66)] = 1922,
  [SMALL_STATE(67)] = 1936,
  [SMALL_STATE(68)] = 1950,
  [SMALL_STATE(69)] = 1964,
  [SMALL_STATE(70)] = 1978,
  [SMALL_STATE(71)] = 1992,
  [SMALL_STATE(72)] = 2006,
  [SMALL_STATE(73)] = 2020,
  [SMALL_STATE(74)] = 2034,
  [SMALL_STATE(75)] = 2060,
  [SMALL_STATE(76)] = 2086,
  [SMALL_STATE(77)] = 2109,
  [SMALL_STATE(78)] = 2132,
  [SMALL_STATE(79)] = 2155,
  [SMALL_STATE(80)] = 2178,
  [SMALL_STATE(81)] = 2201,
  [SMALL_STATE(82)] = 2219,
  [SMALL_STATE(83)] = 2239,
  [SMALL_STATE(84)] = 2259,
  [SMALL_STATE(85)] = 2277,
  [SMALL_STATE(86)] = 2297,
  [SMALL_STATE(87)] = 2312,
  [SMALL_STATE(88)] = 2323,
  [SMALL_STATE(89)] = 2336,
  [SMALL_STATE(90)] = 2346,
  [SMALL_STATE(91)] = 2360,
  [SMALL_STATE(92)] = 2374,
  [SMALL_STATE(93)] = 2388,
  [SMALL_STATE(94)] = 2397,
  [SMALL_STATE(95)] = 2408,
  [SMALL_STATE(96)] = 2419,
  [SMALL_STATE(97)] = 2430,
  [SMALL_STATE(98)] = 2441,
  [SMALL_STATE(99)] = 2452,
  [SMALL_STATE(100)] = 2460,
  [SMALL_STATE(101)] = 2468,
  [SMALL_STATE(102)] = 2476,
  [SMALL_STATE(103)] = 2484,
  [SMALL_STATE(104)] = 2492,
  [SMALL_STATE(105)] = 2500,
  [SMALL_STATE(106)] = 2508,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_music_content, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(21),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(102),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(9),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(16),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(86),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(96),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(60),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(64),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat1, 2), SHIFT_REPEAT(87),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_beam, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pitch_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pitch_repeat1, 2), SHIFT_REPEAT(6),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pitch_repeat1, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pitch, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pitch, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pitch, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pitch, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pitch, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pitch, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(102),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(9),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(16),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(86),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(75),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_cstrct_repeat1, 2), SHIFT_REPEAT(87),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 6),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 8),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 8),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 5),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 5),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 7),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 7),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 4),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 4),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 5),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 5),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 4),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 4),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_construct, 7),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_construct, 7),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_construct_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_construct_repeat1, 2), SHIFT_REPEAT(86),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_note_construct_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nte_or_chrd, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nte_or_chrd, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_cstrct, 9),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chord_cstrct, 9),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grace_note, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grace_note, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_note, 4),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_note, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol, 6),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_note, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_note, 2),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol, 5),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol, 4),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grace_note_repeat1, 2), SHIFT_REPEAT(102),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grace_note_repeat1, 2), SHIFT_REPEAT(9),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grace_note_repeat1, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decoration, 1),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol_note, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord_symbol_note, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_beam_repeat2, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_beam_repeat2, 2), SHIFT_REPEAT(5),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multimeasure_rest, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [319] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ABC(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
